version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-transcription"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9yyuq2jp3iur"
s3_prefix = "serverless-transcription"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "InputBucketName=\"ai-transcribe-media-bucket\" TranscriptionBucketName=\"ai-transcribe-transcription-bucket\""

