AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless trascription

Parameters:
  InputBucketName:
    Type: String
    Default: 'ai-transcribe-media-bucket'
  InputVideoBucketName:
    Type: String
    Default: 'ai-transcribe-video-bucket'
  TranscriptionBucketName:
    Type: String
    Default: 'ai-transcribe-transcription-bucket'
  EFSpath:
    Type: String
    Default: /mnt/efs
  AccessPointARN:
    Type: String
    Description: Access point ARN

Globals:
  Function:
    Timeout: 10

Resources:
  TranscriptionsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref TranscriptionBucketName
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 30
            Status: Enabled
      Tags:
        - Key: Project
          Value: serverless-transcription
  MediaS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref InputBucketName
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 1
            Status: Enabled
      Tags:
        - Key: Project
          Value: serverless-transcription
  VideoS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref InputVideoBucketName
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 1
            Status: Enabled
      Tags:
        - Key: Project
          Value: serverless-transcription


  TranscribeFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: transcriptionJobStartFunction/
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Tags:
        Project: serverless-transcription
      Environment:
        Variables:
          TRANSCRIPTIONS_OUTPUT_BUCKET: !Ref TranscriptionsBucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref InputBucketName
        - S3CrudPolicy:
            BucketName: !Ref TranscriptionBucketName
        - Statement:
          - Effect: Allow
            Resource: '*'
            Action:
              - transcribe:StartTranscriptionJob
              - cloudwatch:GetMetricStatistics
              - cloudwatch:ListMetrics
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref MediaS3Bucket
            Events: s3:ObjectCreated:*

  TranscoderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: transcoderFunction/
      Timeout: 300
      MemorySize: 3008
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          AUDIO_OUTPUT_BUCKET: !Ref MediaS3Bucket
          EFS_FILEPATH: !Ref EFSpath
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref VideoS3Bucket
            Events: s3:ObjectCreated:*
      FileSystemConfigs:
        - Arn: !Ref AccessPointARN
          LocalMountPath: !Ref EFSpath
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref InputBucketName
        - S3CrudPolicy:
            BucketName: !Ref InputVideoBucketName
        - Sid: AmazonElasticFileSystemClientFullAccess
          Effect: Allow
          Action:
            - elasticfilesystem:ClientMount
            - elasticfilesystem:ClientRootAccess
            - elasticfilesystem:ClientWrite
            - elasticfilesystem:DescribeMountTargets
          Resource: "*"

Outputs: 
  S3OutputBucketName:
    Description: Transcriber S3 bucket
    Value: !Ref TranscriptionsBucket
  S3InputBucketName:
    Description: Media S3 bucket
    Value: !Ref MediaS3Bucket